#!/usr/bin/env python3
''' Script to find out details of a node, given its name
- Looks for the node across all our stacks
- Shows Pods running on it, First the ones with problems

So far I just got the first, unrelated example, taken from
https://www.ianlewis.org/en/quick-look-kubernetes-python-client

TODO: Get this script to work fine
TODO: Do a similar one but for pods
'''

import os
from kubernetes import client, config



def load_configs():
  list_configs = []
  configpath = os.path.join(os.environ["HOME"], '.kube')
  for file in os.listdir(configpath):
    if file.startswith("config."):
      list_configs.append(os.path.join(configpath, file))

  return list_configs

def show_allpods(env):
  print('--------------> ' + env)
  #TODO: This does not update itself
  config.load_kube_config(env)

  v1 = client.CoreV1Api()

  pod_list = v1.list_namespaced_pod("default")
  for pod in pod_list.items:
    print("%s\t%s\t%s" % (pod.metadata.name,
                          pod.status.phase,
                          pod.status.pod_ip))


for env in load_configs():
  show_allpods(env)

